apiVersion: v1
kind: Pod
metadata:
  name: cm-env-demo
  namespace: cka
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo APP_ENV=$APP_ENV APP_PORT=$APP_PORT && sleep 3600"]
    env:
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:
          name: app-env
          key: APP_ENV
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: app-env
          key: APP_PORT
  restartPolicy: Never
